[mlol]
website = "mlol_web.site"
username = "username"
password = "password"

[pressreader]
username = "username"
password = "password"

# Optional
[notification_service]
TELEGRAM_BASE_URL = "https://api.telegram.org/bot"
TELEGRAM_TOKEN = "token/"
TELEGRAM_CHAT_ID = 6259
