name: Deploy Release of PressReadmePlease

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  RELEASE_VERSION: ${RELEASE_VERSION}

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8.4", "3.9", "3.10.4"]

    steps:
      - uses: actions/checkout@v3

      - name: Setting up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Installing Poetry Dependencies
        run: |
          pip install poetry
          poetry update
          poetry install

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 --config .flake8 src/ tests/
        continue-on-error: false

      - name: Install Chromium & Playwright Dependencies
        run: |
          poetry run playwright install chromium
          poetry run playwright install-deps chromium

      - name: Launching Tests
        run: |
          poetry run pytest -ra -s -vv

      - name: Build Docker Container
        run: |
          echo "Building PressReadmePlease $RELEASE_VERSION"
          docker build -t tatoalo/pressreader-automation:v$RELEASE_VERSION -t tatoalo/pressreader-automation:latest .

      - name: Authenticate to GHCR
        run: |
          echo "Logging into GHCR"
          docker login ghcr.io -u ${CR_USERNAME} -p ${GHCR_TOKEN}

      - name: Authenticate to DockerHub
        run: |
          echo "Logging into DockerHub"
          docker login -u="${CR_USERNAME}" -p="${DOCKER_HUB_TOKEN}

      - name: Push Docker Container to GHCR
        run: |
          echo "Publishing PressReadmePlease $RELEASE_VERSION ~ GHCR.io"
          docker push --all-tags ghcr.io/${CR_USERNAME}/pressreader-automation

      - name: Push Docker Container to DockerHub
        run: |
          echo "Publishing PressReadmePlease $RELEASE_VERSION ~ DockerHub"
          docker push --all-tags tatoalo/pressreader-automation
